server:
  port: 10011
spring:
  application:
    name: leyou-gateway

eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
    register-with-eureka: true # 把自己注册到eureka服务列表
    fetch-registry: true # 拉取eureka服务信息
  server:
    enable-self-preservation: false # 关闭自我保护
    eviction-interval-timer-in-ms: 1000 # 每隔5秒钟，进行一次服务列表的清理

zuul:
  prefix: /gateway # 路由路径前缀
  routes:
    item-service: /item/**
    auth-service: /auth/**
    user-service: /user/**
    search-service: /search/**
    cart-service: /cart/**
    # 订单微服务
    order-service: /**
  # 携带转发前的头信息
  add-host-header: true
  # zuul过滤器敏感头设置为空
  sensitive-headers:
#    upload-service: /upload/**
#    item-service:
#      path: /gateway/item/**
#      serviceId: item-service

ribbon:
  ConnectTimeout: 4000 # 连接超时时间(ms)
  ReadTimeout: 2000 # 通信超时时间(ms)
  OkToRetryOnAllOperations: true # 是否对所有操作重试
  MaxAutoRetriesNextServer: 1 # 同一服务不同实例的重试次数
  MaxAutoRetries: 1 # 同一实例的重试次数
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMillisecond: 10000 # 熔断超时时长：10000ms

leyou:
  jwt:
    # 公匙地址
    pubKeyPath: D:\development\leyou-code\rsa.pub
    # cookie的key
    cookieName: LY_TOKEN
    
  # 自定义白名单
  filter:
    allowPaths:
      # 登录认证
      - /gateway/auth
      - /gateway/search
      - /gateway/user/register
      - /gateway/user/check
      - /gateway/user/send
      - /gateway/item