server:
  port: 10011
spring:
  application:
    name: leyou-gateway
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
    register-with-eureka: true # 把自己注册到eureka服务列表
    fetch-registry: true # 拉取eureka服务信息
  server:
    enable-self-preservation: false # 关闭自我保护
    eviction-interval-timer-in-ms: 1000 # 每隔5秒钟，进行一次服务列表的清理

zuul:
  prefix: /gateway # 路由路径前缀
  routes:
    item-service: /item/**
    auth-service: /auth/**
    user-service: /user/**

#    upload-service: /upload/**
#    item-service:
#      path: /gateway/item/**
#      serviceId: item-service


leyou:
  jwt:
    # 公匙地址
    pubKeyPath: D:\development\leyou-code\rsa.pub
    # cookie的key
    cookieName: LY_TOKEN
    
  # 自定义白名单
  filter:
    allowPaths:
      # 登录认证
      - /gateway/auth
      - /gateway/search
      - /gateway/user/register
      - /gateway/user/check
      - /gateway/user/send
      - /gateway/item