server:
  port: 10011
spring:
  application:
    name: leyou-gateway
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
    register-with-eureka: true # 把自己注册到eureka服务列表
    fetch-registry: true # 拉取eureka服务信息
  server:
    enable-self-preservation: false # 关闭自我保护
    eviction-interval-timer-in-ms: 1000 # 每隔5秒钟，进行一次服务列表的清理

zuul:
  prefix: /gateway # 路由路径前缀
  routes:
    item-service: /item/**
#    upload-service: /upload/**
#    item-service:
#      path: /gateway/item/**
#      serviceId: item-service
