server:
  port: 8888
spring:
  application:
    name: auth-service
#  rabbitmq:
#    host: 192.168.25.110
#    username: leyou
#    password: leyou
#    virtual-host: /leyou
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
  instance:
    lease-renewal-interval-in-seconds: 5 # 每隔5秒发送一次心跳
    lease-expiration-duration-in-seconds: 10 # 10秒不发送就过期
leyou:
  jwt:
    # 生成公匙和私匙需要的密匙
    secret: hiofsdjhfodsfsd45454356JOJ@@#
    # 公匙地址
    pubKeyPath: D:\development\leyou-code\rsa.pub
    # 私匙地址
    priKeyPath: D:\development\leyou-code\rsa.pri
    # 过期时间,单位分钟
    expire: 30
    # cookie的key
    cookieName: LY_TOKEN
    # cookie过期时间
    cookieMaxAge: 30