server:
  port: 8848
spring:
  application:
    name: user-service
  datasource:
    url: jdbc:mysql://localhost:3306/leyou_mall_plush
    username: root
    password: 123456
# Eureka
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
  instance:
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 10