server:
  port: 7612
spring:
  application:
    name: order-service
  datasource:
    url: jdbc:mysql://localhost:3306/leyou_mall_plush
    username: root
    password: 123456
    hikari:
      max-lifetime: 28830000 # 一个连接的生命时长（毫秒），超时而且没被使用则被释放（retired），缺省:30分钟，建议设置比数据库超时时长少30秒，参考MySQL wait_timeout参数（show variables like '%timeout%';）
      maximum-pool-size: 9 # 连接池中允许的最大连接数。缺省值：10；推荐的公式：((core_count * 2) + effective_spindle_count)
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    virtual-host: /
# Eureka
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
  instance:
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 10

# mybatis
mybatis:
  type-aliases-package: com.leyou.order.pojo
  mapper-locations: classpath*:mybatis/*.xml
  # 控制台打印sql
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true
pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countSql

leyou:
  jwt:
    # 公匙地址
    pubKeyPath: D:\development\leyou-code\rsa.pub
    # cookie的key
    cookieName: LY_TOKEN

  # 雪花算法
  worker:
    workerId: 1
    dataCenterId: 1
  # 微信支付
  pay:
    appId: wx8397f8696b538317
    mchId: 1473426802
    key: T6m9iK73b0kn9g5v426MKfHQH7X8rKwb
    connectTimeoutMs: 5000
    readTimeoutMs: 10000